/**
 * Covered infrastructure products (CVE risk via /v1/check).
 * Keep in sync with Attestd-website/lib/products.ts when adding products.
 */
export const COVERED_PRODUCTS: ReadonlyArray<{ slug: string; display: string }> = [
  { slug: "cassandra", display: "Apache Cassandra" },
  { slug: "couchdb", display: "Apache CouchDB" },
  { slug: "apache_derby", display: "Apache Derby" },
  { slug: "couchbase", display: "Couchbase Server" },
  { slug: "elasticsearch", display: "Elasticsearch" },
  { slug: "mariadb", display: "MariaDB" },
  { slug: "mssql", display: "Microsoft SQL Server" },
  { slug: "mongodb", display: "MongoDB" },
  { slug: "mysql", display: "MySQL" },
  { slug: "oracle_db", display: "Oracle Database" },
  { slug: "postgresql", display: "PostgreSQL" },
  { slug: "redis", display: "Redis" },
  { slug: "sqlite", display: "SQLite" },
  { slug: "apache_httpd", display: "Apache HTTP Server" },
  { slug: "caddy", display: "Caddy" },
  { slug: "haproxy", display: "HAProxy" },
  { slug: "nginx", display: "NGINX" },
  { slug: "squid", display: "Squid" },
  { slug: "traefik", display: "Traefik" },
  { slug: "varnish", display: "Varnish Cache" },
  { slug: "apache_activemq", display: "Apache ActiveMQ" },
  { slug: "apache_kafka", display: "Apache Kafka" },
  { slug: "apache_pulsar", display: "Apache Pulsar" },
  { slug: "mosquitto", display: "Mosquitto" },
  { slug: "rabbitmq", display: "RabbitMQ" },
  { slug: "zeromq", display: "ZeroMQ" },
  { slug: "argo_cd", display: "Argo CD" },
  { slug: "containerd", display: "containerd" },
  { slug: "docker_engine", display: "Docker Engine" },
  { slug: "helm", display: "Helm" },
  { slug: "kube_apiserver", display: "Kubernetes API Server" },
  { slug: "kubelet", display: "Kubernetes kubelet" },
  { slug: "runc", display: "runc" },
  { slug: "envoy", display: "Envoy Proxy" },
  { slug: "istio", display: "Istio" },
  { slug: "cilium", display: "Cilium" },
  { slug: "calico", display: "Calico" },
  { slug: "consul", display: "HashiCorp Consul" },
  { slug: "tomcat", display: "Apache Tomcat" },
  { slug: "jetty", display: "Jetty" },
  { slug: "log4j", display: "Apache Log4j" },
  { slug: "microsoft_exchange", display: "Microsoft Exchange Server" },
  { slug: "openssh", display: "OpenSSH" },
  { slug: "vmware_esxi", display: "VMware ESXi" },
  { slug: "hashicorp_vault", display: "HashiCorp Vault" },
  { slug: "jenkins", display: "Jenkins" },
  { slug: "gitlab", display: "GitLab" },
  { slug: "gitea", display: "Gitea" },
  { slug: "tekton", display: "Tekton Pipelines" },
  { slug: "deno", display: "Deno" },
  { slug: "hermes", display: "Hermes" },
  { slug: "nodejs", display: "Node.js" },
  { slug: "vm2", display: "vm2" },
  { slug: "keycloak", display: "Keycloak" },
  { slug: "openldap", display: "OpenLDAP" },
  { slug: "freeipa", display: "FreeIPA" },
  { slug: "linux_pam", display: "Linux-PAM" },
  { slug: "samba", display: "Samba" },
  { slug: "mit_kerberos", display: "MIT Kerberos" },
  { slug: "python", display: "Python" },
  { slug: "ruby", display: "Ruby" },
  { slug: "php", display: "PHP" },
  { slug: "go", display: "Go" },
  { slug: "openjdk", display: "OpenJDK" },
  { slug: "rust", display: "Rust" },
  { slug: "perl", display: "Perl" },
  { slug: "erlang", display: "Erlang/OTP" },
];
export const COVERED_PRODUCT_COUNT = 67 as const;
